spring:
  profiles:
    active: dev

  application:
    name: woj-common
logging:
  pattern:
    dateformat: yyyy-MM-dd HH:mm:ss:SSS


emailUtil:
  hostName: smtp.qq.com
  charset: UTF-8
  account: 3153917921@qq.com
  password: unijbjmgvfspdddb
  name: AcKing

redis:
  tokenExpire: 259200;
  secret: "23e2q1exd2q1e4dxq14edxq2145rq23r5fasdasdq2wed21qed2q1edq21"
