spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/woj
    username: root
    password: 2W0x0y40706@
  session:
    redis:
     flush-mode: on_save
     save-mode: always
     namespace: "coderjia:session"
  data:
    redis:
      host: localhost
      port: 6379
      password: root@123456
      jedis:
        pool:
          min-idle: 10 #连接池中的最小空闲连接
          max-idle: 50 #连接池中的最大空闲连接
          max-active: 200 #连接池最大连接数（使用负值表示没有限制）
          max-wait: 2000 #连接池最大阻塞等待时间（使用负值表示没有限制）


server:
  port: 8104

mybatis-plus:
  global-config:
    db-config:
      # 全局逻辑删除字段
      logic-delete-field: isDelete
      # 逻辑删除值
      logic-delete-value: 1
      # 逻辑未删除值
      logic-not-delete-value: 0
  configuration:
    map-underscore-to-camel-case: false

# springdoc-openapi项目配置
springdoc:
  api-docs:
    path: /v3/api-docs
# knife4j的增强配置，不需要增强可以不配
knife4j:
  enable: true
  setting:
    language: zh_cn

# spring 事务管理日志
logging:
  level:
    org.springframework.jdbc.support.JdbcTransactionManager: debug

#自定义代码代码沙箱的输出地址，默认为false，使用项目目录下的questionCode作为文件的输出地址，开启后将使用指定的地址
path:
  code:
    submit-code-path: "D:\\Desktop\\WOJ\\NEW\\WOJ\\WOJ\\submitcode"
    judgecase-path: "D:\\Desktop\\WOJ\\NEW\\WOJ\\WOJ\\judgecase"
  avatar:
    user-avatar-path: "D:\\Desktop\\WOJ\\NEW\\WOJ\\WOJ\\avatar\\user"
    course-avatar-path: "D:\\Desktop\\WOJ\\NEW\\WOJ\\WOJ\\avatar\\course"
    activity-avatar-path: "D:\\Desktop\\WOJ\\NEW\\WOJ\\WOJ\\avatar\\activity"

