spring:
  # 数据库配置
  datasource:
    driver-class-name: com.mysql.cj.jdbc.Driver
    url: jdbc:mysql://localhost:3306/woj
    username: root
    password: 2W0x0y40706@
  session:
    redis:
      flush-mode: on_save
      save-mode: always
      namespace: "coderjia:session"
  data:
    redis:
      host: localhost
      port: 6379
      password: root@123456
      jedis:
        pool:
          min-idle: 10 #连接池中的最小空闲连接
          max-idle: 50 #连接池中的最大空闲连接
          max-active: 200 #连接池最大连接数（使用负值表示没有限制）
          max-wait: 2000 #连接池最大阻塞等待时间（使用负值表示没有限制）

  application:
    name: woj-gateway
  main:
    web-application-type: reactive
  cloud:
    nacos:
      discovery:
        server-addr: 127.0.0.1:8848
    gateway:
      routes:
        - id: woj-user-service
          uri: lb://woj-user-service
          predicates:
            - Path=/api/user/**
        - id: woj-web-service
          uri: lb://woj-web-service
          predicates:
            - Path=/api/web/**
        - id: woj-judge-service
          uri: lb://woj-judge-service
          predicates:
            - Path=/api/judge/**
server:
  port: 8101

knife4j:
  gateway:
    # ① 第一个配置，开启gateway聚合组件
    enabled: true
    # ② 第二行配置，设置聚合模式采用discover服务发现的模式
    strategy: discover
    discover:
      # ③ 第三行配置，开启discover模式
      enabled: true
      # ④ 第四行配置，聚合子服务全部为Swagger2规范的文档
      version: openapi3

emailUtil:
  hostName: smtp.qq.com
  charset: UTF-8
  account: 3153917921@qq.com
  password: unijbjmgvfspdddb
  name: AcKing
